(
 ("default"   . ((user-emacs-directory . "~/.doom-emacs.d")
               (server-name . "doom")))
 ("doom"      . ((user-emacs-directory . "~/.doom-emacs.d")
               (server-name . "doom")))
 ("spacemacs" . ((user-emacs-directory . "~/.spacemacs-emacs.d")
               (server-name . "spacemacs")))
 ("zhe"       . ((user-emacs-directory . "~/.zhe-emacs.d")
               (server-name . "zhe")))
 )
