#!/bin/bash
#xrandr --dpi 92
#xrandr --output DP2-2 --primary
#i3-msg '[workspace="^(1|4|6)"] move workspace to output DP2-2;'
#i3-msg '[workspace="^(2|5|9)"] move workspace to output DP2-3;'
#i3-msg '[workspace="^(3|8)"] move workspace to output DP2-1;'
#exec --no-startup-id $HOME/.config/polybar/launch.sh
i3-msg reload
i3-msg restart
